Support for Lua scripting added, try /lua help first. But it's VERY HOT, dxirc maybe unexpect crash
git-svn-id: http://dxirc.googlecode.com/svn/trunk@160 ad0a5998-b8b9-11dd-9d36-1d0c09c95ed7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -595,6 +595,8 @@ LTLIBOBJS
 LIBOBJS
 FOX_CONFIG
 CXXCPP
+LUA_LIBS
+LUA_CFLAGS
 SSL_LIBS
 SSL_CFLAGS
 PKG_CONFIG
@@ -752,6 +754,7 @@ with_included_gettext
 with_libintl_prefix
 enable_tray
 enable_ssl
+enable_lua
 enable_debug
 enable_release
 '
@@ -770,6 +773,8 @@ CCC
 PKG_CONFIG
 SSL_CFLAGS
 SSL_LIBS
+LUA_CFLAGS
+LUA_LIBS
 CXXCPP'
 
 
@@ -1398,6 +1403,7 @@ Optional Features:
   --disable-rpath         do not hardcode runtime library paths
   --disable-tray          Disable trayicon
   --disable-ssl           Disable Secure Sockets Layer support
+  --enable-lua            Enable Lua scripting
   --enable-debug          compile for debugging
   --enable-release        compile for release (advanced optimizations)
 
@@ -1427,6 +1433,8 @@ Some influential environment variables:
   PKG_CONFIG  path to pkg-config utility
   SSL_CFLAGS  C compiler flags for SSL, overriding pkg-config
   SSL_LIBS    linker flags for SSL, overriding pkg-config
+  LUA_CFLAGS  C compiler flags for LUA, overriding pkg-config
+  LUA_LIBS    linker flags for LUA, overriding pkg-config
   CXXCPP      C++ preprocessor
 
 Use these variables to override the choices made by `configure' or to help
@@ -10771,6 +10779,110 @@ $as_echo "#define HAVE_OPENSSL 1" >>confdefs.h
     LIBS="$LIBS $SSL_LIBS"
   fi
 fi
+
+# Check whether --enable-lua was given.
+if test "${enable_lua+set}" = set; then :
+  enableval=$enable_lua; enable_lua=yes
+else
+  enable_lua=no
+fi
+
+have_lua=no
+if test "$enable_lua" = "yes"; then
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for LUA" >&5
+$as_echo_n "checking for LUA... " >&6; }
+
+if test -n "$LUA_CFLAGS"; then
+    pkg_cv_LUA_CFLAGS="$LUA_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua>=5.1\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "lua>=5.1") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_LUA_CFLAGS=`$PKG_CONFIG --cflags "lua>=5.1" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$LUA_LIBS"; then
+    pkg_cv_LUA_LIBS="$LUA_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua>=5.1\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "lua>=5.1") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_LUA_LIBS=`$PKG_CONFIG --libs "lua>=5.1" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        LUA_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "lua>=5.1" 2>&1`
+        else
+	        LUA_PKG_ERRORS=`$PKG_CONFIG --print-errors "lua>=5.1" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$LUA_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+                :
+elif test $pkg_failed = untried; then
+	:
+else
+	LUA_CFLAGS=$pkg_cv_LUA_CFLAGS
+	LUA_LIBS=$pkg_cv_LUA_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
+  if test "$LUA_LIBS"; then
+    CXXFLAGS="${CXXFLAGS} $LUA_CFLAGS"
+    have_lua=yes
+  else
+    for ac_header in lua.h lauxlib.h
+do :
+  as_ac_Header=`$as_echo "ac_cv_header_$ac_header" | $as_tr_sh`
+ac_fn_c_check_header_mongrel "$LINENO" "$ac_header" "$as_ac_Header" "$ac_includes_default"
+eval as_val=\$$as_ac_Header
+   if test "x$as_val" = x""yes; then :
+  cat >>confdefs.h <<_ACEOF
+#define `$as_echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+ LUA_LIBS="-llua"  have_lua=yes
+fi
+
+done
+
+  fi
+  if test "$have_lua" = "yes"; then
+
+$as_echo "#define HAVE_LUA 1" >>confdefs.h
+
+    LIBS="$LIBS $LUA_LIBS"
+  fi
+fi
+
 
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for fxfindfox in -lFOX-1.6" >&5
 $as_echo_n "checking for fxfindfox in -lFOX-1.6... " >&6; }
